### ISSUE TITLE
When do subCollections update in relation to `change` events?

### ISSUE THREAD

**Issue by cmalven** [AmpersandJS/ampersand-state#130]
I'm running into an issue where the order of operations is not what I expect, and I'm not sure how it's supposed to work or how to get around it.

**Issue:** In the following, I would prefer the `change:selected` callback for `models/ingredient.coffee` to always take place after the collection's subCollection has been updated. It isn't. The first time an ingredient's `selected` property is updated, the callback's `console.log` will output `0` (when it should output `1`). When another ingredient becomes `selected`, the output will be `1` (as opposed to `2`) If one of those ingredients becomes un-`selected`, the output will be `2`.

So, it seems that the subCollection isn't being updated until after the `change` event, which makes things difficult.

Assuming this is the desired behavior, what is a good way to work around this and still give each `ingredient` model a way of knowing which of its sibling models is `selected`?

Collection: `models/ingredients.coffee`

```
module.exports = Collection.extend

  initialize: ->
    @selectedIngredients = new SubCollection @,
      where:
        selected: true
  
  model: Ingredient
```

Model: `models/ingredient.coffee`

```
module.exports = State.extend
  
  initialize: ->
    @listenTo @collection, 'change:selected', (evt) =>

      console.log(@collection.selectedIngredients.length)
…
```

View: `views/ingredient.coffee`

```
module.exports = View.extend

  template: ingredientTemplate

  events:
    'click': 'handleClick'

  bindings:

    'model.selected':
      type: 'booleanClass'
      hook: 'title'
      name: 'is-selected'

  render: ->
    @renderWithTemplate()

  handleClick: ->
    @model.toggle('selected')
```
